apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    database: k6
    orgId: 1
    url: http://influxdb:8086

  - name: Prometheus 
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
