{
 "title": "Online Store VNext",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Online API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Api Instances",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(application_operation_total{operation=\"online_store_api_count\"})"
    }
   ]
  },
  {
   "title": "Request By Instances",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 3, "y": 1 },
   "targets": [
    {
     "expr": "avg(application_operation_total{operation=\"order_request_count\",component=\"online_api\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Successful Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(application_operation_total{operation=\"order_success_count\"})"
    }
   ]
  },
  {
   "title": "Api Performance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(application_operation_duration_seconds) by(component,operation)",
     "legendFormat": "{{component}}-{{operation}}"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(application_operation_total{operation=\"order_request_count\"})"
    }
   ]
  },
  {
   "title": "Request Per Second",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 3, "y": 5 },
   "targets": [
    {
     "expr": "sum(rate(application_operation_total{operation=\"order_request_count\",component=\"online_api\"}[1m]))",
     "legendFormat": "RPS"
    }
   ]
  },
  {
   "title": "UnSuccessful Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(application_operation_total{operation=\"order_error_count\"})"
    }
   ]
  },
  { "title": "Inventory Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Api Instances",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(application_operation_total{operation=\"inventory_service_count\"})"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(application_operation_total{operation=\"products_inventory_count\"})"
    }
   ]
  },
  {
   "title": "Request By Instances",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 6, "y": 10 },
   "targets": [
    {
     "expr": "avg(application_operation_total{operation=\"products_inventory_count\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Request Per Second",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 10, "x": 14, "y": 10 },
   "targets": [
    {
     "expr": "sum(rate(application_operation_total{operation=\"products_inventory_count\"}[1m]))",
     "legendFormat": "RPS"
    }
   ]
  },
  { "title": "Shipping Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Api Instances",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(application_operation_total{operation=\"shipping_service_count\"})"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(application_operation_total{operation=\"shipping_info_count\"})"
    }
   ]
  },
  {
   "title": "Request By Instances",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 6, "y": 15 },
   "targets": [
    {
     "expr": "avg(application_operation_total{operation=\"shipping_info_count\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Request Per Second",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 10, "x": 14, "y": 15 },
   "targets": [
    {
     "expr": "sum(rate(application_operation_total{operation=\"shipping_info_count\"}[1m]))",
     "legendFormat": "RPS"
    }
   ]
  },
  { "title": "Accounting", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Consumer Instances",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(application_operation_total{operation=\"accounting_service_count\"})"
    }
   ]
  },
  {
   "title": "Sqs Message Received",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(application_operation_total{operation=\"sqs_message_received_count\"})"
    }
   ]
  },
  {
   "title": "Request By Consumer",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 6, "y": 20 },
   "targets": [
    {
     "expr": "avg(application_operation_total{operation=\"sqs_message_received_count\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Commands Per Second",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 10, "x": 14, "y": 20 },
   "targets": [
    {
     "expr": "sum(rate(application_operation_total{operation=\"sqs_message_received_count\"}[1m]))",
     "legendFormat": "RPS"
    }
   ]
  }
 ]
}