# my global config
global:
  scrape_interval:     1s
  evaluation_interval: 5s
  # scrape_timeout is set to the global default (10s).

scrape_configs:
  - job_name: prometheus

    static_configs:
      - targets: 
        - 'localhost:9090'

  - job_name: online-store-vnext-job

    static_configs:
      - targets: 
        - 'store-api-1:5000'
        - 'store-api-2:5000'
        - 'store-api-3:5000'
        - 'inventory-service-1:5000'
        - 'inventory-service-2:5000'
        - 'inventory-service-3:5000'
        - 'shipping-service-1:5000'
        - 'shipping-service-2:5000'
        - 'shipping-service-3:5000'
        - 'accounting-service-1:5000'
        - 'accounting-service-2:5000'
        - 'accounting-service-3:5000'
  
    metrics_path: /_system/metrics-text